language: python
sudo: required
os:
  - linux

dist: focal

python:
  - "3.8"

install:
  - mkdir ~/.bin
  - PATH=~/.bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
  - chmod a+x ~/.bin/repo
  - mkdir WORKSPACE
  - cd WORKSPACE
  - yes Y | repo init -u https://github.com/AOSPA/manifest -b quartz 
  - yes Y | repo sync -c --no-clone-bundle --current-branch --no-tags -j4 
  - ./rom-build.sh lavender
  - pip install -r requirements.txt

script:
  - pyinstaller --onefile speed.py