language: python
sudo: required
os:
  - linux

dist: focal

python:
  - "3.8"

install:
  - sudo apt update
  - sudo apt install xubuntu-desktop
  - pip install -r requirements.txt

script:
  - pyinstaller --onefile speed.py